version: '3.8'

networks:
    laravel:

services:
    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        ports:
            - "${NGINX_HOST_PORT}:${NGINX_DOCKER_CONTAINER_PORT}"
        volumes:
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./:/var/www
        depends_on:
            - php
            - mysql
        networks:
            - laravel
    mysql:
        image: mysql:8.0.21
        command: --default-authentication-plugin=mysql_native_password
        container_name: mysql
        restart: unless-stopped
        tty: true
        volumes:
            - ./mysql:/var/lib/mysql
        ports:
            - "${MYSQL_HOST_PORT}:${MYSQL_DOCKER_CONTAINER_PORT}"
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: root
            SERVICE_TAG: dev
            SERVICE_NAME: mysql
        networks:
            - laravel
    php:
        build:
            context: .
            dockerfile: Dockerfile
        working_dir: /var/www
        container_name: php
        volumes:
            - ./:/var/www
            - ./php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
        ports:
            - "${PHP_HOST_PORT}:${PHP_DOCKER_CONTAINER_PORT}"
        networks:
            - laravel
